# Generated by Django 4.1.7 on 2023-03-22 14:46

import accounts.managers
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "__first__"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[
                ("object", accounts.managers.UserManager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="commented_posts",
            field=models.ManyToManyField(
                related_name="user_comments",
                to="posts.post",
                verbose_name="Прокомментированные публикации",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="liked_posts",
            field=models.ManyToManyField(
                related_name="user_likes",
                to="posts.post",
                verbose_name="Понравившиеся публикации",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="subscriptions",
            field=models.ManyToManyField(
                related_name="subscribers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписки",
            ),
        ),
    ]
