# Generated by Django 4.1.7 on 2023-03-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_managers_account_commented_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='detail_info',
            field=models.CharField(max_length=200, null=True, verbose_name='Описание_пользователя'),
        ),
    ]
