# Generated by Django 4.1.7 on 2023-03-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_detail_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='liked_posts',
        ),
    ]
