# Generated by Django 4.1.6 on 2023-04-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_liked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='user_pic/1645335859_1-phonoteka-org-p-anime-fon-mafiya-1.jpg', null=True, upload_to='user_pic', verbose_name='Аватар'),
        ),
    ]
